name: Metrics
on:
  # Schedule daily refresh
  schedule: [{ cron: "0 0 * * *" }]
  # Or run manually
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header
          config_timezone: Australia/Brisbane
          committer_message: "chore: update header metrics"
          output_action: pull-request
          users_ignored:
            github-actions[bot], renovate[bot], dependabot[bot],
            dependabot-preview[bot], actions-user, action@github.com

  repositories:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: repositories
          config_timezone: Australia/Brisbane
          committer_message: "chore: update repo metrics"
          output_action: pull-request
          users_ignored:
            github-actions[bot], renovate[bot], dependabot[bot],
            dependabot-preview[bot], actions-user, action@github.com

  activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: activity, community
          config_timezone: Australia/Brisbane
          committer_message: "chore: update activity metrics"
          output_action: pull-request
          users_ignored:
            github-actions[bot], renovate[bot], dependabot[bot],
            dependabot-preview[bot], actions-user, action@github.com

  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          plugin_habits: yes
          plugin_habits_trim: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          config_timezone: Australia/Brisbane
          committer_message: "chore: update habit metrics"
          output_action: pull-request
          users_ignored:
            github-actions[bot], renovate[bot], dependabot[bot],
            dependabot-preview[bot], actions-user, action@github.com

  wakatime:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_days: 30
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          config_timezone: Australia/Brisbane
          committer_message: "chore: update wakatime metrics"
          output_action: pull-request

  achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: compact
          config_timezone: Australia/Brisbane
          committer_message: "chore: update achievement metrics"
          output_action: pull-request
          users_ignored:
            github-actions[bot], renovate[bot], dependabot[bot],
            dependabot-preview[bot], actions-user, action@github.com

  calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 1
          config_timezone: Australia/Brisbane
          committer_message: "chore: update calendar metrics"
          output_action: pull-request-squash
          users_ignored:
            github-actions[bot], renovate[bot], dependabot[bot],
            dependabot-preview[bot], actions-user, action@github.com
