name: Metrics
on:
  # Schedule daily refresh
  schedule: [{ cron: "0 0 * * *" }]
  # Or run manually
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: arrrgi
          template: classic
          base: header
          config_timezone: Australia/Brisbane
          committer_message: "chore: update metrics"

  repositories:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: arrrgi
          template: classic
          base: repositories
          config_timezone: Australia/Brisbane
          committer_message: "chore: update metrics"

  activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: arrrgi
          template: classic
          base: activity, community
          config_timezone: Australia/Brisbane
          committer_message: "chore: update metrics"

  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: arrrgi
          template: classic
          base: ""
          config_timezone: Australia/Brisbane
          committer_message: "chore: update metrics"
          plugin_habits: yes
          plugin_habits_trim: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
